### ISSUE TITLE
Feature request ezydata-mongodb to perform a case-insensitive search

### ISSUE THREAD

**Issue by Assambra** [youngmonkeys/ezydata#27]
**Is your feature request related to a problem? Please describe.**

public Account getAccountByUsername(String username)
{
        return accountRepo.findByField("username", username);
}

does not match if the username in database is "Paul" and the given String username is "paul" 

**Describe the solution you'd like**

It should be a solution or query that have a option to case-insensitive search so that String "paul" match in database with "Paul", "PAUL", "paul", "pAUl", .

e.g.
findByField("username", username, true); or findByField("username", username, false); Or some separate function to get this behaviour.

**Describe alternatives you've considered**

---

**Additional context**

---

**Comment by tvd12** [comment]
I think you can store the username is lowercase then when you find, you can lowercase you keyword, HDYT?

**Comment by Assambra** [comment]
Storing usernames lowercase its not what im looking for. If i read it from the database all names lower cased but the user want to name his character pAUL and not paul. 
Lets say we have two character one named Paul and another one paul i didnt want that it should be string based a unique charactername. And the user have the choise to name his character lower upercase like he want.
In my special case i have a password reset if the user send paul but in db named Paul if wouldt match and he cant reset the password.



# Usage of regular expression with case insesnsitive 
db.student.find({ name: /alice/i })

Some Article about
https://sparkbyexamples.com/mongodb/mongodb-query-case-insensitive/?expand_article=1

# Usage of regular expression with case insesnsitive 
db.student.find({ name: /alice/i })

**Comment by tvd12** [comment]
Could you try https://www.mongodb.com/docs/manual/core/index-case-insensitive/ to create your index and try find again?

**Comment by Assambra** [comment]
Case insensitive searching in mongo db works now. In my case create the collection first

mongosh:
db.createCollection("account", { collation: { locale: 'en_US', strength: 2 } } )
db.account.createIndex( { username: 1 } )

Thank you for your help and your last link that solved my problem
and you can close the issue.
