### ISSUE TITLE
Feature request ezydata-mongodb, write single value in collection without loading and saving the whole object

### ISSUE THREAD

**Issue by Assambra** [youngmonkeys/ezydata#28]
**Is your feature request related to a problem? Please describe.**
public void SetNewPassword(Long id, String password)
    {
        Account account = accountRepo.findById(id);
        account.setPassword(password);
        accountRepo.save(account);
    }

i need to save the whole account object instead of saving only the required field password

**Describe the solution you'd like**
there should be get some function to save only a single value by id like 
saveValueById(id, "field-in-the-collection", value)
Same for a get a single value
Int/String value = getValueById(id, "field-in-the-collection")

There are a lot of usecases to need only save a single value instead of the full object. like Character stats, inventory(load a inventory Object with 100 entries rewrite a single value and write it back to db) maybe isnt good for server performance and for large Objects.

**Describe alternatives you've considered**

**Additional context**

**Comment by tvd12** [comment]
You can use update query, could you take a look the document? https://youngmonkeys.org/ezydata/guides/ezymongo-query-data

**Comment by Assambra** [comment]
Is there an example in code in the book example how to create a custom query?

**Comment by tvd12** [comment]
Could you take a look https://github.com/youngmonkeys/ezydata/blob/master/ezydata-mongodb/src/test/java/com/tvd12/ezydata/mongodb/testing/bean/FoodRepo.java#L50?
I will update the document tomorrow.

**Comment by Assambra** [comment]
Thank you, ive created a custom mongoDB query

@EzyQuery("{$query: {_id:?0}, $update: {$set: {?1:?2}}}")
    void updateStringFieldById(long id, String field, String value);

i think you can close this issue.
